# Generated by Django 6.0.1 on 2026-03-08 16:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hirers', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('work_date', models.DateField()),
                ('work_time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.PositiveIntegerField(default=8, help_text='Expected hours of work')),
                ('description', models.TextField(blank=True, help_text='Description of work to be done')),
                ('offered_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to='hirers.hirerprofile')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(help_text="Describe the worker's performance in detail")),
                ('is_approved', models.BooleanField(default=True, help_text='Admin can hide inappropriate reviews')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='hirers.hirerprofile')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='jobs.joboffer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='workers.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, help_text='Leave blank for state-level rate', max_length=100)),
                ('skill', models.CharField(max_length=50)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily wage in INR', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'district', 'skill'],
                'unique_together': {('state', 'district', 'skill')},
            },
        ),
    ]
