# Generated by Django 6.0.1 on 2026-04-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_fake',
            field=models.BooleanField(default=False, help_text='Flagged as fake by ML model'),
        ),
    ]
