# Generated by Django 6.0.1 on 2026-03-08 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='workers/photos/')),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('aadhar_card_image', models.ImageField(blank=True, null=True, upload_to='workers/aadhar/')),
                ('village_town', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Delhi', 'Delhi')], max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('full_address', models.TextField()),
                ('primary_skill', models.CharField(choices=[('construction', 'Construction & Building'), ('agriculture', 'Agriculture & Farming'), ('domestic', 'Domestic Work'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical Work'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('driving', 'Driving'), ('loading', 'Loading & Unloading'), ('cleaning', 'Cleaning'), ('gardening', 'Gardening'), ('cooking', 'Cooking'), ('tailoring', 'Tailoring'), ('masonry', 'Masonry'), ('welding', 'Welding'), ('other', 'Other')], max_length=50)),
                ('secondary_skills', models.CharField(blank=True, help_text='Comma-separated', max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('brief_intro', models.TextField(help_text='Tell about your work experience')),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('rating_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Blockchain-style score for verification accuracy', max_digits=10)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workers/portfolio/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='workers.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('relation', models.CharField(help_text='e.g., Former employer, Neighbour', max_length=50)),
                ('village_town', models.CharField(max_length=100)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='workers.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_received', to='workers.workerprofile')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_given', to='workers.workerprofile')),
            ],
            options={
                'unique_together': {('new_worker', 'verifier')},
            },
        ),
    ]
