# Generated by Django 6.0.1 on 2026-04-28 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerverification',
            name='is_fake_review',
            field=models.BooleanField(default=False, help_text='ML flagged this verification comment as fake'),
        ),
        migrations.AddField(
            model_name='workerverification',
            name='verifier_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Score (1-5) verifier gives the new worker based on past experience', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='workerverification',
            name='comments',
            field=models.TextField(blank=True, help_text='Describe your experience working with this person'),
        ),
    ]
